instance_url: "https://INSTANCE"
api_token: "TOKEN"
responses:
  - "Without a doubt"
  - "Ask again later"
  - "Don't count on it"
  - "It is certain"
  - "Most likely"
  - "Signs point to yes"
  - "Very doubtful"
  - "The stars are not aligned"
  - "Better not tell you now"
  - "My sources say no"
  - "Yes, definitely"
  - "Cannot predict now"
  - "As I see it, yes"
  - "Don't count on it"
  - "It is decidedly so"
  - "My sources say no but it would be really funny"
  - "Signs point to no… wait, yes!"
  - "Yes definitely… not."
  - "It is decidedly so… unfortunately."
  - "Ask again later, I'm napping."
  - "Most likely you'll regret this question."
  - "Yes definitely maybe."
  - "Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow"
  - "The stars say no, but I say yes!"
  - "Better not tell you now, but I can tell you that I'm a cat."
  - "I don't know."
  - "I don't know the answer to that. Can I help you with a question related to Minecraft?"

